table _Measures
	lineageTag: d5ce0ed3-7f03-4a85-be25-3f25719f29ae

	measure 'Margin %' =
			
			DIVIDE( [Profit], [Sales], 0 )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: adba81ca-30d3-4bbe-bade-f3df646bb6ab

	measure Profit =
			
			[Sales] - [COGS]
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: 8bc9f273-0af0-4837-95a1-6e95d92ace89

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure Sales =
			
			COALESCE( SUM ( SalesFact[Sales] ), 0 )
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: 8f279f6e-0ff6-4793-9d5d-4c67da78d000

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure COGS =
			
			COALESCE( SUM ( SalesFact[COGS] ), 0 )
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: 998172d2-bc9c-448e-9f87-2fdb012b204b

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Sales Card Display' =
			
			DIVIDE ( [Sales], 1000000000 )
		formatString: 0.00"Bn د.ع.‏";-0.00"Bn د.ع.‏";0.00"Bn د.ع.‏"
		lineageTag: a1b2c3d4-0001-4000-8000-000000000001

	measure 'COGS Card Display' =
			
			DIVIDE ( [COGS], 1000000000 )
		formatString: 0.00"Bn د.ع.‏";-0.00"Bn د.ع.‏";0.00"Bn د.ع.‏"
		lineageTag: a1b2c3d4-0002-4000-8000-000000000002

	measure 'Profit Card Display' =
			
			DIVIDE ( [Profit], 1000000 )
		formatString: 0.00"M د.ع.‏";-0.00"M د.ع.‏";0.00"M د.ع.‏"
		lineageTag: a1b2c3d4-0003-4000-8000-000000000003

	measure 'Active BP Count' =
			
			DISTINCTCOUNT( SalesFact[CardCode] )
		formatString: #,0
		lineageTag: a1b2c3d4-0004-4000-8000-000000000004

	measure 'Active Salesperson Count' =
			
			DISTINCTCOUNT( SalesFact[SlpCode] )
		formatString: #,0
		lineageTag: a1b2c3d4-0005-4000-8000-000000000005

	measure 'Avg Sales per BP' =
			
			DIVIDE( [Sales], [Active BP Count], 0 )
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: a1b2c3d4-0006-4000-8000-000000000006

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Avg Sales per Salesperson' =
			
			DIVIDE( [Sales], [Active Salesperson Count], 0 )
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: a1b2c3d4-0007-4000-8000-000000000007

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Total Qty' =
			
			COALESCE( SUM( SalesFact[Qty] ), 0 )
		formatString: #,0
		lineageTag: a1b2c3d4-0008-4000-8000-000000000008

	measure 'Rebate Achievement %' =
			
			DIVIDE(
			    CALCULATE( SUM( BP_Rebate_Fact[Sales] ), BP_Rebate_Fact[SortKey] <= 4 ),
			    CALCULATE( SUM( BP_Rebate_Fact[Target] ), BP_Rebate_Fact[SortKey] <= 4 ),
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a1b2c3d4-0009-4000-8000-000000000009

	measure 'Total Target' =
			
			COALESCE( CALCULATE( SUM( BP_Rebate_Fact[Target] ), BP_Rebate_Fact[SortKey] <= 4 ), 0 )
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: a1b2c3d4-000a-4000-8000-000000000010

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Total Rebate' =
			
			COALESCE( CALCULATE( SUM( BP_Rebate_Fact[RebateAmount] ), BP_Rebate_Fact[SortKey] <= 4 ), 0 )
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: a1b2c3d4-000b-4000-8000-000000000011

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Rebate Sales' =
			
			COALESCE( CALCULATE( SUM( BP_Rebate_Fact[Sales] ), BP_Rebate_Fact[SortKey] <= 4 ), 0 )
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: a1b2c3d4-000c-4000-8000-000000000012

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Commission Total Target' =
			
			COALESCE( CALCULATE( SUM( Commission_Fact[Target] ), Commission_Fact[SortKey] <= 4, Commission_Fact[SlpCode] <> 160, Commission_Fact[SlpCode] <> 161, Commission_Fact[SlpCode] <> 167 ), 0 )
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: cf01a2b3-da01-4000-8000-000000000001

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Commission Total Sales' =
			
			COALESCE( CALCULATE( SUM( Commission_Fact[Sales] ), Commission_Fact[SortKey] <= 4, Commission_Fact[SlpCode] <> 160, Commission_Fact[SlpCode] <> 161, Commission_Fact[SlpCode] <> 167 ), 0 )
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: cf01a2b3-da02-4000-8000-000000000002

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Total Commission' =
			
			COALESCE( CALCULATE( SUM( Commission_Fact[CommissionAmount] ), Commission_Fact[SortKey] <= 4, Commission_Fact[SlpCode] <> 160, Commission_Fact[SlpCode] <> 161, Commission_Fact[SlpCode] <> 167 ), 0 )
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: cf01a2b3-da03-4000-8000-000000000003

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Commission Achievement %' =
			
			DIVIDE(
			    [Commission Total Sales],
			    [Commission Total Target],
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: cf01a2b3-da04-4000-8000-000000000004

	measure 'Commission Row Target' =
			
			IF(
			    ISINSCOPE( Commission_Fact[SlpName] ),
			    CALCULATE( SUM( Commission_Fact[Target] ), Commission_Fact[SortKey] <= 4 ),
			    CALCULATE( SUM( Commission_Fact[Target] ), Commission_Fact[SortKey] <= 4, Commission_Fact[SlpCode] <> 160, Commission_Fact[SlpCode] <> 161, Commission_Fact[SlpCode] <> 167 )
			)
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: cf01a2b3-da05-4000-8000-000000000005

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Commission Row Sales' =
			
			IF(
			    ISINSCOPE( Commission_Fact[SlpName] ),
			    CALCULATE( SUM( Commission_Fact[Sales] ), Commission_Fact[SortKey] <= 4 ),
			    CALCULATE( SUM( Commission_Fact[Sales] ), Commission_Fact[SortKey] <= 4, Commission_Fact[SlpCode] <> 160, Commission_Fact[SlpCode] <> 161, Commission_Fact[SlpCode] <> 167 )
			)
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: cf01a2b3-da06-4000-8000-000000000006

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Commission Row Amount' =
			
			IF(
			    ISINSCOPE( Commission_Fact[SlpName] ),
			    CALCULATE( SUM( Commission_Fact[CommissionAmount] ), Commission_Fact[SortKey] <= 4 ),
			    CALCULATE( SUM( Commission_Fact[CommissionAmount] ), Commission_Fact[SortKey] <= 4, Commission_Fact[SlpCode] <> 160, Commission_Fact[SlpCode] <> 161, Commission_Fact[SlpCode] <> 167 )
			)
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: cf01a2b3-da07-4000-8000-000000000007

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Commission Row Achievement %' =
			
			DIVIDE( [Commission Row Sales], [Commission Row Target], 0 )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: cf01a2b3-da08-4000-8000-000000000008

	measure 'Comp Is Month View' =

			IF (
			    ISFILTERED ( DateTable[Month] )
			        || ISFILTERED ( DateTable[MonthYear] )
			        || ISFILTERED ( DateTable[YearMonth] ),
			    1,
			    0
			)
		formatString: 0
		lineageTag: 5a6b7c8d-0001-4000-8000-000000000001

	measure 'Comp Row Visible' =

			VAR SAPActiveValue = SELECTEDVALUE ( CommissionEmployee[SAPActive] )
			RETURN
			    IF ( SAPActiveValue = "Y", 1, 0 )
		formatString: 0
		lineageTag: 5a6b7c8d-0002-4000-8000-000000000002

	measure 'Comp Department Background Color' =

			VAR DepartmentValue = SELECTEDVALUE ( CommissionEmployee[Department] )
			RETURN
			    SWITCH (
			        TRUE (),
			        DepartmentValue = "Direct", "#EAF2FF",
			        DepartmentValue = "Indirect", "#EAF7EF",
			        DepartmentValue = "Online", "#F3EDFF",
			        DepartmentValue = "Service", "#FFF4DF",
			        DepartmentValue = "End User", "#EAF7FF",
			        DepartmentValue = "Resellers", "#F0F7EA",
			        DepartmentValue = "Others", "#F4F6F8",
			        DepartmentValue = "Needs Plan Setup", "#F4F6F8",
			        DepartmentValue = "Unassigned", "#F4F6F8",
			        "#FFFFFF"
			    )
		lineageTag: 5a6b7c8d-0036-4000-8000-000000000036

	measure 'Comp Selected Period Count' =

			VAR MonthCount =
			    MAX ( 1, DISTINCTCOUNT ( DateTable[MonthNumber] ) )
			VAR QuarterCount =
			    MAX ( 1, DISTINCTCOUNT ( DateTable[Quarter] ) )
			RETURN
			    IF (
			        [Comp Is Month View] = 1,
			        MonthCount,
			        IF (
			            ISFILTERED ( DateTable[Quarter] )
			                || ISFILTERED ( DateTable[YearQuarter] )
			                || ISFILTERED ( DateTable[QuarterKey] ),
			            QuarterCount,
			            4
			        )
			    )
		formatString: 0
		lineageTag: 5a6b7c8d-0015-4000-8000-000000000015

	measure 'Comp Row Salary' =

			IF (
			    [Comp Row Visible] = 1,
			    SELECTEDVALUE ( CommissionEmployee[Salary] )
			)
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: 5a6b7c8d-0003-4000-8000-000000000003

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Comp Salary' =

			IF (
			    ISINSCOPE ( CommissionEmployee[SalesPerson] ),
			    [Comp Row Salary],
			    SUMX (
			        FILTER ( VALUES ( CommissionEmployee[SalesPerson] ), [Comp Row Visible] = 1 ),
			        [Comp Row Salary]
			    )
			)
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: 5a6b7c8d-0004-4000-8000-000000000004

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Comp Row Target' =

			IF (
			    [Comp Row Visible] = 1,
			    IF (
			        [Comp Is Month View] = 1,
			        SELECTEDVALUE ( CommissionEmployee[MonthlyTarget] ) * [Comp Selected Period Count],
			        SELECTEDVALUE ( CommissionEmployee[QuarterTarget] ) * [Comp Selected Period Count]
			    )
			)
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: 5a6b7c8d-0005-4000-8000-000000000005

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Comp Target' =

			IF (
			    ISINSCOPE ( CommissionEmployee[SalesPerson] ),
			    [Comp Row Target],
			    SUMX (
			        FILTER ( VALUES ( CommissionEmployee[SalesPerson] ), [Comp Row Visible] = 1 ),
			        [Comp Row Target]
			    )
			)
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: 5a6b7c8d-0006-4000-8000-000000000006

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Comp Row Actual' =

			VAR IsVisible = [Comp Row Visible] = 1
			VAR PlanGroupValue = SELECTEDVALUE ( CommissionEmployee[PlanGroup] )
			VAR SlpCodeValue = SELECTEDVALUE ( CommissionEmployee[SlpCode] )
			RETURN
			    IF (
			        NOT IsVisible,
			        BLANK (),
			        SWITCH (
			            TRUE (),
			            PlanGroupValue = "ServiceTeam",
			                CALCULATE (
			                    [Sales],
			                    REMOVEFILTERS ( DimSalesperson ),
			                    REMOVEFILTERS ( SalesFact[SlpCode] ),
			                    REMOVEFILTERS ( SalesFact[SalesPerson] ),
			                    SalesFact[SalesDept] IN { "Service Office", "Service Production" }
			                ),
			            NOT ISBLANK ( SlpCodeValue ),
			                CALCULATE (
			                    [Sales],
			                    TREATAS ( { SlpCodeValue }, SalesFact[SlpCode] )
			                ),
			            BLANK ()
			        )
			    )
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: 5a6b7c8d-0007-4000-8000-000000000007

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Comp Actual' =

			IF (
			    ISINSCOPE ( CommissionEmployee[SalesPerson] ),
			    [Comp Row Actual],
			    SUMX (
			        FILTER ( VALUES ( CommissionEmployee[SalesPerson] ), [Comp Row Visible] = 1 ),
			        [Comp Row Actual]
			    )
			)
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: 5a6b7c8d-0008-4000-8000-000000000008

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Comp Achievement %' =

			DIVIDE ( [Comp Actual], [Comp Target], 0 )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5a6b7c8d-0009-4000-8000-000000000009

	measure 'Comp Payout %' =

			VAR TargetValue = [Comp Target]
			VAR ActualValue = [Comp Actual]
			RETURN
			    SWITCH (
			        TRUE (),
			        ISBLANK ( TargetValue ), BLANK (),
			        [Comp Is Month View] = 1 && ActualValue >= TargetValue, 1,
			        [Comp Is Month View] = 1, 0.75,
			        ActualValue >= TargetValue, 1,
			        0
			    )
		formatString: 0%;-0%;0%
		lineageTag: 5a6b7c8d-0010-4000-8000-000000000010

	measure 'Comp Row Payable' =

			VAR TargetValue = [Comp Row Target]
			VAR ActualValue = [Comp Row Actual]
			VAR SalaryValue = SELECTEDVALUE ( CommissionEmployee[Salary] )
			VAR IncentiveValue = SELECTEDVALUE ( CommissionEmployee[QuarterIncentive] )
			VAR PeriodCount = [Comp Selected Period Count]
			RETURN
			    SWITCH (
			        TRUE (),
			        [Comp Row Visible] <> 1, BLANK (),
			        ISBLANK ( TargetValue ), BLANK (),
			        [Comp Is Month View] = 1 && ActualValue >= TargetValue, SalaryValue * PeriodCount,
			        [Comp Is Month View] = 1, SalaryValue * 0.75 * PeriodCount,
			        ActualValue >= TargetValue, IncentiveValue * PeriodCount,
			        0
			    )
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: 5a6b7c8d-0011-4000-8000-000000000011

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Comp Payable' =

			IF (
			    ISINSCOPE ( CommissionEmployee[SalesPerson] ),
			    [Comp Row Payable],
			    SUMX (
			        FILTER ( VALUES ( CommissionEmployee[SalesPerson] ), [Comp Row Visible] = 1 ),
			        [Comp Row Payable]
			    )
			)
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: 5a6b7c8d-0012-4000-8000-000000000012

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Comp Review Note' =

			VAR StatusValue = SELECTEDVALUE ( CommissionEmployee[EmployeeStatus] )
			VAR PlanNote = SELECTEDVALUE ( CommissionEmployee[ReviewNote] )
			VAR TargetValue = [Comp Row Target]
			RETURN
			    SWITCH (
			        TRUE (),
			        StatusValue = "Inactive", "Inactive in SAP",
			        StatusValue = "Needs Plan Setup", "Needs Plan Setup",
			        StatusValue = "Needs SAP Match", "Needs SAP Match",
			        NOT ISBLANK ( PlanNote ) && PlanNote <> "", PlanNote,
			        ISBLANK ( TargetValue ), "Missing target",
			        [Comp Actual] >= TargetValue, "Achieved",
			        "Below target"
			    )
		lineageTag: 5a6b7c8d-0013-4000-8000-000000000013

	measure 'Comp Needs Review Count' =

			SUMX (
			    FILTER ( VALUES ( CommissionEmployee[SalesPerson] ), [Comp Row Visible] = 1 ),
			    VAR StatusValue = SELECTEDVALUE ( CommissionEmployee[EmployeeStatus] )
			    VAR TargetValue = [Comp Row Target]
			    VAR PlanNote = SELECTEDVALUE ( CommissionEmployee[ReviewNote] )
			    RETURN
			        IF (
			            StatusValue <> "Active"
			                || ISBLANK ( TargetValue )
			                || ( NOT ISBLANK ( PlanNote ) && PlanNote <> "" ),
			            1,
			            0
			        )
			)
		formatString: #,0
		lineageTag: 5a6b7c8d-0014-4000-8000-000000000014

	measure 'Monthly Salary Period Count' =

			IF (
			    ISFILTERED ( DateTable[Month] )
			        || ISFILTERED ( DateTable[MonthYear] )
			        || ISFILTERED ( DateTable[YearMonth] ),
			    MAX ( 1, DISTINCTCOUNT ( DateTable[YearMonthKey] ) )
			)
		formatString: 0
		lineageTag: 5a6b7c8d-0016-4000-8000-000000000016

	measure 'Monthly Salary Target' =

			VAR PeriodCount = [Monthly Salary Period Count]
			RETURN
			    IF (
			        ISINSCOPE ( CommissionEmployee[SalesPerson] ),
			        IF ( [Comp Row Visible] = 1, SELECTEDVALUE ( CommissionEmployee[MonthlyTarget] ) * PeriodCount ),
			        SUMX (
			            FILTER ( VALUES ( CommissionEmployee[SalesPerson] ), [Comp Row Visible] = 1 ),
			            SELECTEDVALUE ( CommissionEmployee[MonthlyTarget] ) * PeriodCount
			        )
			    )
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: 5a6b7c8d-0017-4000-8000-000000000017

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Monthly Salary Actual' =

			IF (
			    ISBLANK ( [Monthly Salary Period Count] ),
			    BLANK (),
			    IF (
			        ISINSCOPE ( CommissionEmployee[SalesPerson] ),
			        [Comp Row Actual],
			        SUMX (
			            FILTER ( VALUES ( CommissionEmployee[SalesPerson] ), [Comp Row Visible] = 1 ),
			            [Comp Row Actual]
			        )
			    )
			)
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: 5a6b7c8d-0018-4000-8000-000000000018

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Monthly Salary COGS Row' =

			VAR IsVisible = [Comp Row Visible] = 1
			VAR PlanGroupValue = SELECTEDVALUE ( CommissionEmployee[PlanGroup] )
			VAR SlpCodeValue = SELECTEDVALUE ( CommissionEmployee[SlpCode] )
			RETURN
			    IF (
			        NOT IsVisible,
			        BLANK (),
			        SWITCH (
			            TRUE (),
			            PlanGroupValue = "ServiceTeam",
			                CALCULATE (
			                    [COGS],
			                    REMOVEFILTERS ( DimSalesperson ),
			                    REMOVEFILTERS ( SalesFact[SlpCode] ),
			                    REMOVEFILTERS ( SalesFact[SalesPerson] ),
			                    SalesFact[SalesDept] IN { "Service Office", "Service Production" }
			                ),
			            NOT ISBLANK ( SlpCodeValue ),
			                CALCULATE (
			                    [COGS],
			                    TREATAS ( { SlpCodeValue }, SalesFact[SlpCode] )
			                ),
			            BLANK ()
			        )
			    )
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: 5a6b7c8d-0030-4000-8000-000000000030

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Monthly Salary COGS' =

			IF (
			    ISBLANK ( [Monthly Salary Period Count] ),
			    BLANK (),
			    IF (
			        ISINSCOPE ( CommissionEmployee[SalesPerson] ),
			        [Monthly Salary COGS Row],
			        SUMX (
			            FILTER ( VALUES ( CommissionEmployee[SalesPerson] ), [Comp Row Visible] = 1 ),
			            [Monthly Salary COGS Row]
			        )
			    )
			)
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: 5a6b7c8d-0031-4000-8000-000000000031

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Monthly Salary Achievement %' =

			DIVIDE ( [Monthly Salary Actual], [Monthly Salary Target], 0 )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5a6b7c8d-0019-4000-8000-000000000019

	measure 'Monthly Salary Gross Margin Percentage' =

			DIVIDE (
			    [Monthly Salary Actual] - [Monthly Salary COGS],
			    [Monthly Salary Actual],
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5a6b7c8d-0032-4000-8000-000000000032

	measure 'Monthly Salary Base' =

			VAR PeriodCount = [Monthly Salary Period Count]
			RETURN
			    IF (
			        ISINSCOPE ( CommissionEmployee[SalesPerson] ),
			        IF ( [Comp Row Visible] = 1, SELECTEDVALUE ( CommissionEmployee[Salary] ) * PeriodCount ),
			        SUMX (
			            FILTER ( VALUES ( CommissionEmployee[SalesPerson] ), [Comp Row Visible] = 1 ),
			            SELECTEDVALUE ( CommissionEmployee[Salary] ) * PeriodCount
			        )
			    )
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: 5a6b7c8d-0020-4000-8000-000000000020

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Monthly Salary Payout %' =

			VAR TargetValue = [Monthly Salary Target]
			VAR ActualValue = [Monthly Salary Actual]
			VAR PlanGroupValue = SELECTEDVALUE ( CommissionEmployee[PlanGroup] )
			VAR MeetsMarginRule =
			    PlanGroupValue <> "ServiceTeam"
			        || [Monthly Salary Gross Margin Percentage] >= 0.4
			RETURN
			    SWITCH (
			        TRUE (),
			        ISBLANK ( TargetValue ), BLANK (),
			        ISINSCOPE ( CommissionEmployee[SalesPerson] )
			            && ActualValue >= TargetValue
			            && MeetsMarginRule, 1,
			        ISINSCOPE ( CommissionEmployee[SalesPerson] ), 0.75,
			        DIVIDE ( [Monthly Salary Payable], [Monthly Salary Base] )
			    )
		formatString: 0%;-0%;0%
		lineageTag: 5a6b7c8d-0021-4000-8000-000000000021

	measure 'Monthly Salary Payable' =

			VAR PeriodCount = [Monthly Salary Period Count]
			RETURN
			    IF (
			        ISBLANK ( PeriodCount ),
			        BLANK (),
			        SUMX (
			            FILTER ( VALUES ( CommissionEmployee[SalesPerson] ), [Comp Row Visible] = 1 ),
			            VAR TargetValue = SELECTEDVALUE ( CommissionEmployee[MonthlyTarget] ) * PeriodCount
			            VAR ActualValue = [Comp Row Actual]
			            VAR SalaryValue = SELECTEDVALUE ( CommissionEmployee[Salary] ) * PeriodCount
			            VAR PlanGroupValue = SELECTEDVALUE ( CommissionEmployee[PlanGroup] )
			            VAR MeetsMarginRule =
			                PlanGroupValue <> "ServiceTeam"
			                    || [Monthly Salary Gross Margin Percentage] >= 0.4
			            RETURN
			                SWITCH (
			                    TRUE (),
			                    ISBLANK ( TargetValue ), BLANK (),
			                    ActualValue >= TargetValue && MeetsMarginRule, SalaryValue,
			                    SalaryValue * 0.75
			                )
			        )
			    )
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: 5a6b7c8d-0022-4000-8000-000000000022

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Quarter Commission Period Count' =

			VAR QuarterCount =
			    MAX (
			        1,
			        CALCULATE (
			            DISTINCTCOUNT ( DateTable[Quarter] ),
			            REMOVEFILTERS ( DateTable[Month] ),
			            REMOVEFILTERS ( DateTable[MonthNumber] ),
			            REMOVEFILTERS ( DateTable[MonthYear] ),
			            REMOVEFILTERS ( DateTable[YearMonth] ),
			            REMOVEFILTERS ( DateTable[YearMonthKey] )
			        )
			    )
			RETURN
			    IF (
			        ISFILTERED ( DateTable[Quarter] )
			            || ISFILTERED ( DateTable[YearQuarter] )
			            || ISFILTERED ( DateTable[QuarterKey] ),
			        QuarterCount,
			        4
			    )
		formatString: 0
		lineageTag: 5a6b7c8d-0023-4000-8000-000000000023

	measure 'Quarter Commission Target' =

			VAR PeriodCount = [Quarter Commission Period Count]
			RETURN
			    IF (
			        ISINSCOPE ( CommissionEmployee[SalesPerson] ),
			        IF ( [Comp Row Visible] = 1, SELECTEDVALUE ( CommissionEmployee[QuarterTarget] ) * PeriodCount ),
			        SUMX (
			            FILTER ( VALUES ( CommissionEmployee[SalesPerson] ), [Comp Row Visible] = 1 ),
			            SELECTEDVALUE ( CommissionEmployee[QuarterTarget] ) * PeriodCount
			        )
			    )
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: 5a6b7c8d-0024-4000-8000-000000000024

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Quarter Commission Actual Row' =

			VAR PlanGroupValue = SELECTEDVALUE ( CommissionEmployee[PlanGroup] )
			VAR SlpCodeValue = SELECTEDVALUE ( CommissionEmployee[SlpCode] )
			VAR YearValue = SELECTEDVALUE ( DateTable[Year], 2026 )
			RETURN
			    IF (
			        [Comp Row Visible] <> 1,
			        BLANK (),
			        SWITCH (
			            TRUE (),
			            PlanGroupValue = "ServiceTeam",
			                CALCULATE (
			                    [Sales],
			                    REMOVEFILTERS ( DimSalesperson ),
			                    REMOVEFILTERS ( SalesFact[SlpCode] ),
			                    REMOVEFILTERS ( SalesFact[SalesPerson] ),
			                    REMOVEFILTERS ( DateTable[Month] ),
			                    REMOVEFILTERS ( DateTable[MonthNumber] ),
			                    REMOVEFILTERS ( DateTable[MonthYear] ),
			                    REMOVEFILTERS ( DateTable[YearMonth] ),
			                    REMOVEFILTERS ( DateTable[YearMonthKey] ),
			                    KEEPFILTERS ( DateTable[Year] = YearValue ),
			                    SalesFact[SalesDept] IN { "Service Office", "Service Production" }
			                ),
			            NOT ISBLANK ( SlpCodeValue ),
			                CALCULATE (
			                    [Sales],
			                    REMOVEFILTERS ( DateTable[Month] ),
			                    REMOVEFILTERS ( DateTable[MonthNumber] ),
			                    REMOVEFILTERS ( DateTable[MonthYear] ),
			                    REMOVEFILTERS ( DateTable[YearMonth] ),
			                    REMOVEFILTERS ( DateTable[YearMonthKey] ),
			                    KEEPFILTERS ( DateTable[Year] = YearValue ),
			                    TREATAS ( { SlpCodeValue }, SalesFact[SlpCode] )
			                ),
			            BLANK ()
			        )
			    )
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: 5a6b7c8d-0029-4000-8000-000000000029

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Quarter Commission Actual' =

			IF (
			    ISINSCOPE ( CommissionEmployee[SalesPerson] ),
			    [Quarter Commission Actual Row],
			    SUMX (
			        FILTER ( VALUES ( CommissionEmployee[SalesPerson] ), [Comp Row Visible] = 1 ),
			        [Quarter Commission Actual Row]
			    )
			)
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: 5a6b7c8d-0025-4000-8000-000000000025

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Quarter Commission COGS Row' =

			VAR PlanGroupValue = SELECTEDVALUE ( CommissionEmployee[PlanGroup] )
			VAR SlpCodeValue = SELECTEDVALUE ( CommissionEmployee[SlpCode] )
			VAR YearValue = SELECTEDVALUE ( DateTable[Year], 2026 )
			RETURN
			    IF (
			        [Comp Row Visible] <> 1,
			        BLANK (),
			        SWITCH (
			            TRUE (),
			            PlanGroupValue = "ServiceTeam",
			                CALCULATE (
			                    [COGS],
			                    REMOVEFILTERS ( DimSalesperson ),
			                    REMOVEFILTERS ( SalesFact[SlpCode] ),
			                    REMOVEFILTERS ( SalesFact[SalesPerson] ),
			                    REMOVEFILTERS ( DateTable[Month] ),
			                    REMOVEFILTERS ( DateTable[MonthNumber] ),
			                    REMOVEFILTERS ( DateTable[MonthYear] ),
			                    REMOVEFILTERS ( DateTable[YearMonth] ),
			                    REMOVEFILTERS ( DateTable[YearMonthKey] ),
			                    KEEPFILTERS ( DateTable[Year] = YearValue ),
			                    SalesFact[SalesDept] IN { "Service Office", "Service Production" }
			                ),
			            NOT ISBLANK ( SlpCodeValue ),
			                CALCULATE (
			                    [COGS],
			                    REMOVEFILTERS ( DateTable[Month] ),
			                    REMOVEFILTERS ( DateTable[MonthNumber] ),
			                    REMOVEFILTERS ( DateTable[MonthYear] ),
			                    REMOVEFILTERS ( DateTable[YearMonth] ),
			                    REMOVEFILTERS ( DateTable[YearMonthKey] ),
			                    KEEPFILTERS ( DateTable[Year] = YearValue ),
			                    TREATAS ( { SlpCodeValue }, SalesFact[SlpCode] )
			                ),
			            BLANK ()
			        )
			    )
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: 5a6b7c8d-0033-4000-8000-000000000033

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Quarter Commission COGS' =

			IF (
			    ISINSCOPE ( CommissionEmployee[SalesPerson] ),
			    [Quarter Commission COGS Row],
			    SUMX (
			        FILTER ( VALUES ( CommissionEmployee[SalesPerson] ), [Comp Row Visible] = 1 ),
			        [Quarter Commission COGS Row]
			    )
			)
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: 5a6b7c8d-0034-4000-8000-000000000034

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Quarter Commission Achievement %' =

			DIVIDE ( [Quarter Commission Actual], [Quarter Commission Target], 0 )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5a6b7c8d-0026-4000-8000-000000000026

	measure 'Quarter Commission Gross Margin Percentage' =

			DIVIDE (
			    [Quarter Commission Actual] - [Quarter Commission COGS],
			    [Quarter Commission Actual],
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5a6b7c8d-0035-4000-8000-000000000035

	measure 'Quarter Commission Incentive' =

			VAR PeriodCount = [Quarter Commission Period Count]
			RETURN
			    IF (
			        ISINSCOPE ( CommissionEmployee[SalesPerson] ),
			        IF ( [Comp Row Visible] = 1, SELECTEDVALUE ( CommissionEmployee[QuarterIncentive] ) * PeriodCount ),
			        SUMX (
			            FILTER ( VALUES ( CommissionEmployee[SalesPerson] ), [Comp Row Visible] = 1 ),
			            SELECTEDVALUE ( CommissionEmployee[QuarterIncentive] ) * PeriodCount
			        )
			    )
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: 5a6b7c8d-0027-4000-8000-000000000027

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Quarter Commission Earned' =

			IF (
			    ISINSCOPE ( CommissionEmployee[SalesPerson] ),
			    IF (
			        ISBLANK ( [Quarter Commission Target] ),
			        BLANK (),
			        VAR PlanGroupValue = SELECTEDVALUE ( CommissionEmployee[PlanGroup] )
			        VAR MeetsMarginRule =
			            PlanGroupValue <> "ServiceTeam"
			                || [Quarter Commission Gross Margin Percentage] >= 0.4
			        RETURN
			            IF (
			                [Quarter Commission Actual] >= [Quarter Commission Target]
			                    && MeetsMarginRule,
			                [Quarter Commission Incentive],
			                0
			            )
			    ),
			    SUMX (
			        FILTER ( VALUES ( CommissionEmployee[SalesPerson] ), [Comp Row Visible] = 1 ),
			        IF (
			            ISBLANK ( [Quarter Commission Target] ),
			            BLANK (),
			            VAR PlanGroupValue = SELECTEDVALUE ( CommissionEmployee[PlanGroup] )
			            VAR MeetsMarginRule =
			                PlanGroupValue <> "ServiceTeam"
			                    || [Quarter Commission Gross Margin Percentage] >= 0.4
			            RETURN
			                IF (
			                    [Quarter Commission Actual] >= [Quarter Commission Target]
			                        && MeetsMarginRule,
			                    [Quarter Commission Incentive],
			                    0
			                )
			        )
			    )
			)
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: 5a6b7c8d-0028-4000-8000-000000000028

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Mapped Sales' =
			
			CALCULATE ( [Sales], KEEPFILTERS ( Geo_City_Reference[IsMapped] = TRUE() ) )
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: 7d1f5a28-3001-4af7-8a20-304934000001

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Mapped Sales Card Display' =
			
			DIVIDE ( [Mapped Sales], 1000000000 )
		formatString: 0.00"Bn د.ع.‏";-0.00"Bn د.ع.‏";0.00"Bn د.ع.‏"
		lineageTag: 7d1f5a28-3002-4af7-8a20-304934000002

	measure 'Mapped BP Count' =
			
			CALCULATE ( [Active BP Count], KEEPFILTERS ( Geo_City_Reference[IsMapped] = TRUE() ) )
		formatString: #,0
		lineageTag: 7d1f5a28-3003-4af7-8a20-304934000003

	measure 'Mapped City Count' =
			
			COUNTROWS ( FILTER ( VALUES ( Geo_City_Reference[CityName] ), [Mapped Sales] <> 0 ) )
		formatString: #,0
		lineageTag: 7d1f5a28-3004-4af7-8a20-304934000004

	measure 'Unmapped Sales' =
			
			CALCULATE (
			    [Sales],
			    FILTER (
			        DimBusinessPartner,
			        ISBLANK ( DimBusinessPartner[LocationGroupKey] )
			            || NOT CONTAINS (
			                Geo_City_Reference,
			                Geo_City_Reference[LocationGroupKey], DimBusinessPartner[LocationGroupKey]
			            )
			    )
			)
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: 7d1f5a28-3005-4af7-8a20-304934000005

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Unmapped Sales Card Display' =
			
			DIVIDE ( [Unmapped Sales], 1000000000 )
		formatString: 0.00"Bn د.ع.‏";-0.00"Bn د.ع.‏";0.00"Bn د.ع.‏"
		lineageTag: 7d1f5a28-3006-4af7-8a20-304934000006

	measure 'Map Longitude' =
			
			AVERAGE ( Geo_City_Reference[Lon] )
		formatString: 0.0000
		lineageTag: 7d1f5a28-3008-4af7-8a20-304934000008

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Map Latitude' =
			
			AVERAGE ( Geo_City_Reference[Lat] )
		formatString: 0.0000
		lineageTag: 7d1f5a28-3009-4af7-8a20-304934000009

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Map Projected X' =
			
			AVERAGEX ( Geo_City_Reference, Geo_City_Reference[Lon] * PI() / 180 )
		formatString: 0.0000
		lineageTag: 7d1f5a28-3011-4af7-8a20-304934000011

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Map Projected Y' =
			
			AVERAGEX (
			    Geo_City_Reference,
			    LN ( TAN ( PI() / 4 + Geo_City_Reference[Lat] * PI() / 360 ) )
			)
		formatString: 0.0000
		lineageTag: 7d1f5a28-3010-4af7-8a20-304934000010

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Map Bubble Radius' =
			
			POWER ( MAX ( [Mapped Sales], 0 ), 1.0 / 3.0 )
		formatString: #,0
		lineageTag: 7d1f5a28-3007-4af7-8a20-304934000007

	measure 'Iraq Governorate Choropleth SVG' =
			
			VAR _Geo =
			{
				( "Al Anbar", CALCULATE ( [Sales], KEEPFILTERS ( Geo_City_Reference[Governorate] = "Al Anbar" ) ), "M200 190L216 197L247 205L282 204L284 230L306 242L317 233L317 252L329 262L330 266L335 268L335 270L344 279L368 282L372 285L392 286L408 307L399 316L387 316L384 319L397 328L398 342L395 350L384 352L371 359L341 365L379 399L362 410L353 413L337 432L337 439L330 450L330 461L324 465L319 473L318 507L260 465L207 443L145 407L62 393L69 387L66 379L52 383L47 370L54 368L34 308L159 244L182 240L200 214L200 190Z" ),
				( "Al Muthanna", CALCULATE ( [Sales], KEEPFILTERS ( Geo_City_Reference[Governorate] = "Al Muthanna" ) ), "M378 552L393 534L408 500L427 481L431 468L444 445L447 446L457 453L463 439L468 432L463 425L472 425L477 420L513 430L512 442L509 448L511 451L511 465L506 472L503 474L503 483L545 487L554 494L563 506L569 509L569 516L579 531L572 571L572 583L568 589L567 608L559 610L440 601L378 552Z" ),
				( "Al Qadisiyyah", CALCULATE ( [Sales], KEEPFILTERS ( Geo_City_Reference[Governorate] = "Al Qadisiyyah" ) ), "M444 445L428 442L421 433L421 430L426 430L423 422L426 419L425 415L429 411L426 403L427 396L431 393L447 395L448 387L455 385L470 374L482 378L491 384L505 399L508 413L511 417L513 429L477 420L472 425L463 425L468 432L463 439L457 453L447 446L444 445Z" ),
				( "Babil", CALCULATE ( [Sales], KEEPFILTERS ( Geo_City_Reference[Governorate] = "Babil" ) ), "M395 350L398 342L397 328L393 323L388 323L385 320L385 317L399 316L408 321L424 318L429 328L425 337L431 342L440 341L446 348L453 349L460 356L464 357L463 362L469 364L464 368L464 371L470 374L455 385L448 387L446 396L432 393L421 387L415 392L411 393L406 376L396 364L404 353L395 350Z" ),
				( "Baghdad", CALCULATE ( [Sales], KEEPFILTERS ( Geo_City_Reference[Governorate] = "Baghdad" ) ), "M399 316L414 302L428 303L431 305L431 315L429 317L408 321L399 316Z" ),
				( "Basra", CALCULATE ( [Sales], KEEPFILTERS ( Geo_City_Reference[Governorate] = "Basra" ) ), "M567 606L568 589L572 583L572 571L579 531L571 520L567 507L593 498L603 501L602 496L605 485L605 462L611 455L621 453L644 454L644 473L666 473L668 509L676 513L678 519L683 519L692 528L691 533L694 536L696 542L706 548L693 548L680 540L674 539L661 542L646 536L623 535L610 539L603 546L586 585L574 600L567 606Z" ),
				( "Dhi Qar", CALCULATE ( [Sales], KEEPFILTERS ( Geo_City_Reference[Governorate] = "Dhi Qar" ) ), "M512 429L512 419L508 413L508 405L553 404L553 406L549 408L556 413L559 425L569 435L570 445L579 451L580 458L589 464L605 462L605 485L602 496L603 501L593 498L567 507L563 506L554 494L545 487L503 483L503 474L506 472L511 465L511 451L509 448L512 442L514 431L512 429Z" ),
				( "Diyala", CALCULATE ( [Sales], KEEPFILTERS ( Geo_City_Reference[Governorate] = "Diyala" ) ), "M429 328L423 318L431 315L431 305L428 303L414 303L411 296L413 292L417 290L419 284L417 282L417 277L422 271L422 269L418 265L411 264L411 261L416 253L419 252L424 247L423 242L426 231L425 227L428 226L436 231L437 225L440 224L440 217L446 209L458 209L461 206L465 211L472 209L478 224L483 220L491 218L492 212L502 200L501 196L507 189L511 188L513 206L507 209L505 215L510 223L510 228L500 227L496 224L495 231L490 233L491 240L497 242L500 246L497 251L499 255L494 257L487 266L489 268L495 268L505 284L512 289L511 291L522 289L525 293L520 300L526 297L529 300L520 305L517 311L512 313L508 319L501 325L479 321L462 314L452 317L447 325L441 331L435 332L434 328L429 328Z" ),
				( "Duhok", CALCULATE ( [Sales], KEEPFILTERS ( Geo_City_Reference[Governorate] = "Duhok" ) ), "M379 64L363 65L367 72L362 76L354 77L344 70L340 70L336 71L328 82L311 85L309 82L304 84L305 81L301 77L294 79L292 75L287 74L289 66L284 67L280 63L279 56L293 55L298 48L308 40L319 43L332 40L341 44L347 44L355 48L360 47L365 50L375 49L378 51L384 50L387 45L394 43L397 46L397 52L379 64Z" ),
				( "Erbil", CALCULATE ( [Sales], KEEPFILTERS ( Geo_City_Reference[Governorate] = "Erbil" ) ), "M344 149L351 136L350 130L356 128L359 120L377 105L381 98L393 90L402 90L411 83L408 78L394 73L390 68L379 64L397 52L397 46L394 43L409 48L409 54L404 57L408 65L412 65L415 61L422 59L431 53L444 54L442 57L446 61L452 64L453 72L448 78L461 80L464 88L459 95L452 95L446 98L437 95L433 99L430 100L430 109L435 108L436 110L441 112L441 114L432 115L431 120L443 130L452 136L453 138L439 139L432 137L428 140L419 139L414 141L398 140L393 143L379 140L375 144L369 165L360 163L359 169L354 165L352 167L344 161L346 152L344 149Z" ),
				( "Karbala", CALCULATE ( [Sales], KEEPFILTERS ( Geo_City_Reference[Governorate] = "Karbala" ) ), "M341 365L371 359L387 351L403 352L405 355L396 364L408 380L372 393L341 365Z" ),
				( "Kirkuk", CALCULATE ( [Sales], KEEPFILTERS ( Geo_City_Reference[Governorate] = "Kirkuk" ) ), "M424 189L412 212L408 217L394 208L384 205L373 195L346 186L337 168L347 164L353 167L356 165L359 169L360 163L369 165L375 144L379 140L393 143L398 140L414 141L419 139L428 140L433 137L441 140L439 146L444 152L442 159L447 168L440 174L437 182L433 186L424 189Z" ),
				( "Maysan", CALCULATE ( [Sales], KEEPFILTERS ( Geo_City_Reference[Governorate] = "Maysan" ) ), "M605 462L589 464L580 458L579 451L570 445L569 435L559 425L556 413L549 407L553 406L553 403L555 401L553 395L563 390L554 376L561 368L561 361L566 347L564 345L567 342L579 349L588 359L607 370L614 370L618 368L623 370L628 375L628 380L631 381L632 384L636 387L634 394L637 394L642 397L648 407L655 415L655 419L645 443L644 454L613 454L608 458L605 462Z" ),
				( "Najaf", CALCULATE ( [Sales], KEEPFILTERS ( Geo_City_Reference[Governorate] = "Najaf" ) ), "M318 507L319 473L324 465L330 461L330 450L337 439L337 432L353 413L362 410L379 399L372 393L408 380L410 392L415 392L421 387L431 393L426 397L426 405L429 411L425 415L426 419L423 422L426 430L421 430L421 433L428 442L444 446L431 468L427 481L408 500L393 534L378 552L318 507Z" ),
				( "Nineveh", CALCULATE ( [Sales], KEEPFILTERS ( Geo_City_Reference[Governorate] = "Nineveh" ) ), "M282 204L247 205L216 197L200 190L204 165L211 157L211 142L202 127L205 107L212 95L242 90L279 58L284 67L289 66L287 74L292 75L294 79L301 77L305 81L304 84L309 82L311 85L328 82L336 71L340 70L344 70L354 77L362 76L367 72L363 65L371 63L377 63L389 67L394 73L408 78L411 82L406 87L399 91L391 90L381 98L377 105L359 120L356 128L350 130L351 136L347 140L344 150L333 155L322 156L308 167L309 177L322 192L282 193L282 204Z" ),
				( "Salah al-Din", CALCULATE ( [Sales], KEEPFILTERS ( Geo_City_Reference[Governorate] = "Salah al-Din" ) ), "M408 307L392 286L372 285L368 282L344 279L335 270L335 268L330 266L329 262L317 252L317 233L306 242L284 230L282 193L322 192L309 177L308 172L309 165L322 156L333 155L344 149L346 152L343 160L347 164L337 168L346 186L373 195L384 205L394 208L408 217L412 212L424 189L429 192L448 193L454 197L453 208L446 209L440 217L440 224L437 225L436 231L428 226L425 227L426 231L423 242L424 247L419 252L416 253L411 260L411 264L418 265L422 269L422 271L417 277L417 282L419 284L417 290L413 292L411 296L414 303L408 307Z" ),
				( "Sulaymaniyah", CALCULATE ( [Sales], KEEPFILTERS ( Geo_City_Reference[Governorate] = "Sulaymaniyah" ) ), "M453 208L454 199L451 195L429 192L424 189L433 186L437 182L440 174L447 168L442 159L444 152L439 146L441 142L439 139L453 137L431 120L432 115L441 113L435 108L430 109L430 100L438 95L446 98L459 94L467 103L474 102L478 104L478 109L480 112L478 114L481 115L484 124L483 130L484 132L497 131L502 133L511 145L532 141L539 144L550 144L551 146L546 149L531 152L527 156L529 160L526 160L528 163L526 166L528 170L538 180L536 183L541 186L538 191L533 191L531 194L523 191L523 194L520 194L521 199L518 204L513 203L511 188L507 189L501 196L502 200L492 212L491 218L483 220L478 224L472 209L465 211L461 206L458 209L453 208Z" ),
				( "Wasit", CALCULATE ( [Sales], KEEPFILTERS ( Geo_City_Reference[Governorate] = "Wasit" ) ), "M470 374L464 371L464 368L469 364L463 362L464 357L460 356L453 349L446 348L440 341L431 342L424 336L425 334L428 333L429 328L434 328L435 332L441 331L447 325L453 316L462 314L479 321L493 323L500 326L505 322L512 313L517 311L520 305L530 300L533 308L542 317L542 320L538 323L531 325L539 328L535 334L539 337L550 335L567 342L564 345L566 347L561 361L561 368L554 376L563 390L553 395L555 401L553 404L508 405L502 395L491 384L480 377L470 374Z" )
			}
			VAR _NonZero = FILTER ( _Geo, [Value2] > 0 )
			VAR _MinSales = COALESCE ( MINX ( _NonZero, [Value2] ), 0 )
			VAR _MaxSales = COALESCE ( MAXX ( _Geo, [Value2] ), 0 )
			VAR _Range = _MaxSales - _MinSales
			VAR _Paths =
			    CONCATENATEX (
			        _Geo,
			        VAR _Name = [Value1]
			        VAR _Sales = [Value2]
			        VAR _Path = [Value3]
			        VAR _RawRatio =
			            IF (
			                _Sales <= 0,
			                0,
			                IF ( _Range = 0, 1, DIVIDE ( _Sales - _MinSales, _Range, 0 ) )
			            )
			        VAR _Ratio = IF ( _Sales <= 0, 0, 0.18 + 0.82 * POWER ( _RawRatio, 0.45 ) )
			        VAR _R = ROUND ( 235 + ( 8 - 235 ) * _Ratio, 0 )
			        VAR _G = ROUND ( 243 + ( 62 - 243 ) * _Ratio, 0 )
			        VAR _B = ROUND ( 251 + ( 118 - 251 ) * _Ratio, 0 )
			        VAR _Fill = IF ( _Sales <= 0, "#F2F6FA", "rgb(" & _R & "," & _G & "," & _B & ")" )
			        RETURN
			            "<path d='" & _Path & "' fill='" & _Fill & "' stroke='#9FB6CC' stroke-width='1.2' vector-effect='non-scaling-stroke'><title>" & _Name & ": " & FORMAT ( _Sales, "#,0" ) & "</title></path>",
			        ""
			    )
			VAR _Svg =
			    "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 740 650' preserveAspectRatio='xMidYMid meet'>"
			        & "<rect x='0' y='0' width='740' height='650' fill='#FFFFFF'/>"
			        & _Paths
			        & "</svg>"
			RETURN
			    _Svg
		lineageTag: 30493401-0f0e-4a2b-9c8d-000000001001
		dataCategory: ImageUrl

	measure 'Governorate Tooltip Sales' =
			
			IF (
			    NOT SELECTEDVALUE ( Geo_Governorate_Map[IsAnchor], FALSE() ),
			    [Governorate Sales]
			)
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: 30493401-2222-4a2b-9c8d-000000001001

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Governorate Tooltip Customer Count' =
			
			VAR _Governorates = VALUES ( Geo_Governorate_Map[Governorate] )
			RETURN
			    IF (
			        NOT SELECTEDVALUE ( Geo_Governorate_Map[IsAnchor], FALSE() ),
			        CALCULATE (
			            [Mapped BP Count],
			            KEEPFILTERS ( TREATAS ( _Governorates, Geo_City_Reference[Governorate] ) )
			        )
			    )
		formatString: #,0
		lineageTag: 30493401-2222-4a2b-9c8d-000000001002

	measure 'Governorate Tooltip City Count' =
			
			VAR _Governorates = VALUES ( Geo_Governorate_Map[Governorate] )
			RETURN
			    IF (
			        NOT SELECTEDVALUE ( Geo_Governorate_Map[IsAnchor], FALSE() ),
			        CALCULATE (
			            [Mapped City Count],
			            KEEPFILTERS ( TREATAS ( _Governorates, Geo_City_Reference[Governorate] ) )
			        )
			    )
		formatString: #,0
		lineageTag: 30493401-2222-4a2b-9c8d-000000001003

	measure 'Governorate Tooltip Plot X' =
			
			AVERAGE ( Geo_Governorate_Map[PlotX] )
		formatString: 0.0
		lineageTag: 30493401-2222-4a2b-9c8d-000000001004

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Governorate Tooltip Plot Y' =
			
			AVERAGE ( Geo_Governorate_Map[PlotY] )
		formatString: 0.0
		lineageTag: 30493401-2222-4a2b-9c8d-000000001005

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Governorate Tooltip Hit Size' =
			
			MAX ( Geo_Governorate_Map[HitSize] )
		formatString: 0.0
		lineageTag: 30493401-2222-4a2b-9c8d-000000001006

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Governorate Sales % of Total' =
			
			DIVIDE ( [Governorate Sales], [Company Sales], 0 )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 30493401-2222-4a2b-9c8d-000000001007

	measure 'Company Sales' =
			
			CALCULATE (
			    [Sales],
			    REMOVEFILTERS ( DimSalesperson[SalesPerson] ),
			    REMOVEFILTERS ( DimBusinessPartner[CardName] ),
			    REMOVEFILTERS ( DimBusinessPartner[CardCode] ),
			    REMOVEFILTERS ( DimBusinessPartner[GroupCode] ),
			    REMOVEFILTERS ( DimBusinessPartner[GroupName] ),
			    REMOVEFILTERS ( DimBusinessPartner[LocationGroupKey] ),
			    REMOVEFILTERS ( SalesFact[BusinessType] ),
			    REMOVEFILTERS ( SalesFact[U_GroupType] ),
			    REMOVEFILTERS ( SalesFact[U_ProductType] ),
			    REMOVEFILTERS ( SalesFact[U_SegmentType] ),
			    REMOVEFILTERS ( SalesFact[ItemName] ),
			    REMOVEFILTERS ( SalesFact[ItemCode] ),
			    REMOVEFILTERS ( Geo_City_Reference ),
			    REMOVEFILTERS ( Geo_Governorate_Map )
			)
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: 30493401-3333-4a2b-9c8d-000000001001

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	measure 'Sales Share %' =
			
			DIVIDE ( [Sales], [Company Sales], 0 )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 30493401-3333-4a2b-9c8d-000000001002

	measure 'Governorate Sales' =
			
			VAR _Governorates = VALUES ( Geo_Governorate_Map[Governorate] )
			RETURN
			    CALCULATE (
			        [Sales],
			        KEEPFILTERS ( TREATAS ( _Governorates, Geo_City_Reference[Governorate] ) )
			    )
		formatString: #,0\ "د.ع.‏";-#,0\ "د.ع.‏";#,0\ "د.ع.‏"
		lineageTag: 30493401-2222-4a2b-9c8d-000000001008

		annotation PBI_FormatHint = {"currencyCulture":"ar-IQ"}

	column Column1
		dataType: string
		lineageTag: 04e1a892-aafd-4175-a5ce-2ceefa957d05
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

